version: 0.2

phases:
  install:
    commands:
      - echo "Installing Miniconda..."
      - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a

  pre_build:
    commands:
      - echo "Creating Conda environment..."
      - conda env create -f envs/environment.yml

  build:
    commands:
      - echo "Building project..."
      # Add commands to build your project here

  post_build:
    commands:
      - echo "Packaging project..."
      - cd ..
      - tar -czvf stock-ticker-latest.tar.gz ${CODEBUILD_SRC_DIR}

artifacts:
  files:
    - stock-ticker-latest.tar.gz

