version: 0.2
phases:
  pre_build:
    commands:
    - env
    - cat /etc/os-release
    - aws --version

    # Add Docker's official GPG key:
    - apt-get update -y
    - apt-get install -y ca-certificates curl
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc

    # Create a temporary file with the Docker repository configuration:
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /tmp/docker.list

    # Copy the temporary file to the sources.list.d directory:
    - cp /tmp/docker.list /etc/apt/sources.list.d/docker.list

    # Remove the temporary file:
    - rm /tmp/docker.list

    # Install docker
    - apt-get update -y
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - docker --version

    - echo Logging in to Amazon ECR....
    - cat /etc/os-release
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 809784555426.dkr.ecr.us-east-1.amazonaws.com
    - cat ~/.docker/config.json
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=latest
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -f containerfile -t sweng-861:latest .
    - docker tag sweng-861:latest 809784555426.dkr.ecr.us-east-1.amazonaws.com/sweng-861:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo pushing to repo
    - docker push 809784555426.dkr.ecr.us-east-1.amazonaws.com/sweng-861:latest
    - echo Writing image definitions file...
    #- printf '[{"ImageURI":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
    - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - appspec.yml