name: stock-ticker
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - idna=3.6
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.0
  - pip=23.3.2
  - pysocks=1.7.1
  - python=3.10.0
  - python_abi=3.10
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.0.3
  - sqlite=3.44.2
  - tk=8.6.13
  - tzdata=2023d
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - asgiref==3.7.2
      - boto3==1.34.38
      - botocore==1.34.38
      - django==5.0.1
      - jmespath==1.0.1
      - python-dateutil==2.8.2
      - s3transfer==0.10.0
      - six==1.16.0
      - sqlparse==0.4.4
      - typing-extensions==4.9.0
      - urllib3==2.0.7
